import { StyleSheet } from "react-native";

import { ALVO_TOQUE_MINIMO, fonteMono, raios, sombra, type Cores } from "@/constants/theme";

export function criarEstilos(cores: Cores) {
  return StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: cores.fundo,
    },
    flex: {
      flex: 1,
    },
    carregando: {
      marginTop: 40,
    },

    cabecalho: {
      gap: 10,
      paddingHorizontal: 16,
      paddingTop: 12,
      paddingBottom: 10,
      borderBottomWidth: 1,
      borderBottomColor: cores.borda,
      backgroundColor: cores.fundo,
    },
    linhaCabecalho: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 8,
    },
    vendedor: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
    },
    avatar: {
      width: 34,
      height: 34,
      borderRadius: raios.pill,
      backgroundColor: cores.botaoPrimario,
      borderWidth: 2,
      borderColor: cores.primariaFundoForte,
      alignItems: "center",
      justifyContent: "center",
    },
    avatarTexto: {
      fontSize: 13,
      fontWeight: "800",
      color: cores.textoSobreCor,
    },
    indicadorOnline: {
      position: "absolute",
      right: -2,
      bottom: -2,
      width: 11,
      height: 11,
      borderRadius: raios.pill,
      borderWidth: 2,
      borderColor: cores.fundo,
      backgroundColor: cores.sucesso,
    },
    vendedorLinha: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
    },
    vendedorNome: {
      fontSize: 13,
      fontWeight: "800",
      color: cores.textoPrimario,
    },
    seloBalcao: {
      paddingHorizontal: 6,
      paddingVertical: 1,
      borderRadius: 6,
      backgroundColor: cores.primariaFundo,
    },
    seloBalcaoTexto: {
      fontSize: 10,
      fontWeight: "700",
      color: cores.primaria,
    },
    vendedorTerminal: {
      fontSize: 11,
      color: cores.textoTerciario,
    },
    acoesCabecalho: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
    },
    botaoCliente: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      height: 40,
      maxWidth: 140,
      paddingHorizontal: 10,
      borderRadius: raios.sm,
      borderWidth: 1,
      borderColor: cores.borda,
      backgroundColor: cores.superficie,
      ...sombra.cartao,
    },
    botaoClienteTexto: {
      flexShrink: 1,
      fontSize: 12,
      fontWeight: "600",
      color: cores.textoSecundario,
    },
    pontoCliente: {
      width: 7,
      height: 7,
      borderRadius: raios.pill,
      backgroundColor: cores.desabilitado,
    },
    pontoClienteAtivo: {
      backgroundColor: cores.sucesso,
    },
    botaoMenu: {
      width: 40,
      height: 40,
      borderRadius: raios.sm,
      borderWidth: 1,
      borderColor: cores.borda,
      backgroundColor: cores.superficie,
      alignItems: "center",
      justifyContent: "center",
      ...sombra.cartao,
    },
    abas: {
      flexDirection: "row",
      gap: 4,
      padding: 4,
      borderRadius: raios.md,
      backgroundColor: cores.neutroFundoForte,
    },
    aba: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 5,
      height: 38,
      borderRadius: raios.sm,
    },
    abaAtiva: {
      backgroundColor: cores.superficie,
      ...sombra.cartao,
    },
    abaTexto: {
      fontSize: 12,
      fontWeight: "600",
      color: cores.textoSecundario,
    },
    abaTextoAtiva: {
      fontWeight: "700",
      color: cores.primaria,
    },
    abaContador: {
      minWidth: 18,
      height: 18,
      paddingHorizontal: 5,
      borderRadius: raios.pill,
      backgroundColor: cores.botaoPrimario,
      alignItems: "center",
      justifyContent: "center",
    },
    abaContadorTexto: {
      fontSize: 10,
      fontWeight: "800",
      color: cores.textoSobreCor,
    },

    filtros: {
      gap: 10,
      paddingTop: 12,
      paddingBottom: 10,
    },
    campoBusca: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      height: 46,
      marginHorizontal: 16,
      paddingLeft: 14,
      paddingRight: 6,
      borderRadius: raios.md,
      borderWidth: 1,
      borderColor: cores.borda,
      backgroundColor: cores.superficie,
      ...sombra.cartao,
    },
    inputBusca: {
      flex: 1,
      height: "100%",
      fontSize: 14,
      fontWeight: "500",
      color: cores.textoPrimario,
      outlineStyle: "solid",
      outlineWidth: 0,
    },
    botaoLimpar: {
      width: 36,
      height: 36,
      alignItems: "center",
      justifyContent: "center",
    },
    chips: {
      alignItems: "center",
      gap: 6,
      paddingHorizontal: 16,
    },
    segmentado: {
      flexDirection: "row",
      padding: 3,
      borderRadius: raios.sm,
      backgroundColor: cores.neutroFundoForte,
    },
    segmento: {
      height: 30,
      paddingHorizontal: 10,
      borderRadius: 9,
      alignItems: "center",
      justifyContent: "center",
    },
    segmentoAtivo: {
      backgroundColor: cores.superficie,
      ...sombra.cartao,
    },
    segmentoTexto: {
      fontSize: 11,
      fontWeight: "600",
      color: cores.textoSecundario,
    },
    segmentoTextoAtivo: {
      fontWeight: "800",
      color: cores.primaria,
    },
    separadorVertical: {
      width: 1,
      height: 18,
      marginHorizontal: 4,
      backgroundColor: cores.borda,
    },
    chip: {
      height: 32,
      paddingHorizontal: 12,
      borderRadius: raios.pill,
      borderWidth: 1,
      borderColor: cores.borda,
      backgroundColor: cores.superficie,
      alignItems: "center",
      justifyContent: "center",
    },
    chipAtivo: {
      borderColor: cores.botaoPrimario,
      backgroundColor: cores.botaoPrimario,
    },
    chipTexto: {
      fontSize: 11,
      fontWeight: "600",
      color: cores.textoSecundario,
    },
    chipTextoAtivo: {
      color: cores.textoSobreCor,
    },
    lista: {
      flexGrow: 1,
      paddingHorizontal: 16,
      paddingBottom: 16,
    },
    listaComBarra: {
      paddingBottom: 96,
    },
    cabecalhoHistorico: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      marginHorizontal: 16,
      marginTop: 12,
      marginBottom: 10,
      padding: 12,
      borderRadius: raios.md,
      borderWidth: 1,
      borderColor: cores.primariaFundoForte,
      backgroundColor: cores.primariaFundo,
    },
    itemIndisponivel: {
      flexDirection: "row",
      alignItems: "center",
      marginBottom: 10,
      opacity: 0.7,
    },
    vazio: {
      alignItems: "center",
      gap: 6,
      paddingVertical: 36,
      paddingHorizontal: 20,
    },
    vazioTitulo: {
      fontSize: 14,
      fontWeight: "700",
      color: cores.textoPrimario,
    },
    vazioTexto: {
      fontSize: 12,
      textAlign: "center",
      color: cores.textoTerciario,
    },
    botaoVazio: {
      width: undefined,
      marginTop: 8,
      paddingHorizontal: 18,
    },

    barraCarrinho: {
      position: "absolute",
      left: 12,
      right: 12,
      bottom: 12,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 10,
      padding: 10,
      paddingLeft: 14,
      borderRadius: raios.md,
      backgroundColor: cores.toastFundo,
      ...sombra.flutuante,
    },
    barraCarrinhoResumo: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
    },
    barraCarrinhoIcone: {
      width: 36,
      height: 36,
      borderRadius: raios.sm,
      backgroundColor: cores.botaoPrimario,
      alignItems: "center",
      justifyContent: "center",
    },
    barraCarrinhoContador: {
      position: "absolute",
      top: -6,
      right: -6,
      minWidth: 18,
      height: 18,
      paddingHorizontal: 4,
      borderRadius: raios.pill,
      backgroundColor: cores.perigo,
      alignItems: "center",
      justifyContent: "center",
    },
    barraCarrinhoContadorTexto: {
      fontSize: 10,
      fontWeight: "800",
      color: cores.textoSobreCor,
    },
    barraCarrinhoTotal: {
      fontSize: 15,
      fontWeight: "800",
      fontFamily: fonteMono,
      color: cores.toastTexto,
    },
    barraCarrinhoDica: {
      fontSize: 10,
      color: cores.textoTerciario,
    },
    barraCarrinhoBotao: {
      flexDirection: "row",
      alignItems: "center",
      gap: 4,
      height: ALVO_TOQUE_MINIMO,
      paddingHorizontal: 14,
      borderRadius: raios.sm,
      backgroundColor: cores.botaoPrimario,
    },
    barraCarrinhoBotaoTexto: {
      fontSize: 13,
      fontWeight: "700",
      color: cores.textoSobreCor,
    },

    conteudo: {
      gap: 12,
      padding: 16,
      paddingBottom: 32,
    },
    secaoTopo: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
    },
    tituloSecao: {
      fontSize: 18,
      fontWeight: "800",
      color: cores.textoPrimario,
    },
    subtituloSecao: {
      fontSize: 11,
      color: cores.textoTerciario,
    },
    botaoSuave: {
      flexDirection: "row",
      alignItems: "center",
      gap: 3,
      height: 36,
      paddingHorizontal: 12,
      borderRadius: raios.sm,
      backgroundColor: cores.primariaFundo,
    },
    botaoSuaveTexto: {
      fontSize: 12,
      fontWeight: "700",
      color: cores.primaria,
    },
    cartao: {
      gap: 10,
      padding: 14,
      borderRadius: raios.md,
      borderWidth: 1,
      borderColor: cores.borda,
      backgroundColor: cores.superficie,
      ...sombra.cartao,
    },
    cartaoLinha: {
      flexDirection: "row",
      alignItems: "center",
    },
    cartaoCabecalho: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 8,
    },
    iconeCliente: {
      width: 34,
      height: 34,
      borderRadius: raios.sm,
      backgroundColor: cores.neutroFundo,
      alignItems: "center",
      justifyContent: "center",
    },
    rotuloPequeno: {
      fontSize: 10,
      fontWeight: "800",
      letterSpacing: 0.6,
      textTransform: "uppercase",
      color: cores.textoTerciario,
    },
    textoForte: {
      fontSize: 13,
      fontWeight: "700",
      color: cores.textoPrimario,
    },
    textoSuave: {
      fontSize: 11,
      fontWeight: "400",
      color: cores.textoTerciario,
    },
    textoMono: {
      fontSize: 11,
      fontFamily: fonteMono,
      color: cores.textoTerciario,
    },
    link: {
      fontSize: 13,
      fontWeight: "700",
      color: cores.primaria,
    },
    avisoEstoque: {
      marginTop: 2,
      fontSize: 11,
      fontWeight: "700",
      color: cores.alerta,
    },
    linkPerigo: {
      marginTop: 4,
      fontSize: 11,
      fontWeight: "600",
      color: cores.perigo,
    },
    itemCarrinho: {
      flexDirection: "row",
      alignItems: "center",
    },
    itemCarrinhoIcone: {
      fontSize: 22,
    },
    itemCarrinhoDireita: {
      alignItems: "flex-end",
      gap: 6,
    },
    itemCarrinhoTotal: {
      fontSize: 13,
      fontWeight: "800",
      fontFamily: fonteMono,
      color: cores.textoPrimario,
    },
    segmentadoPequeno: {
      flexDirection: "row",
      padding: 3,
      borderRadius: raios.sm - 2,
      backgroundColor: cores.neutroFundoForte,
    },
    segmentoPequeno: {
      minWidth: 40,
      height: 30,
      paddingHorizontal: 8,
      borderRadius: 8,
      alignItems: "center",
      justifyContent: "center",
    },
    campoDesconto: {
      flexDirection: "row",
      alignItems: "center",
      height: ALVO_TOQUE_MINIMO + 2,
      paddingHorizontal: 14,
      borderRadius: raios.sm,
      borderWidth: 1,
      borderColor: cores.borda,
      backgroundColor: cores.superficieAlternativa,
    },
    campoDescontoErro: {
      borderColor: cores.perigo,
    },
    inputDesconto: {
      flex: 1,
      height: "100%",
      fontSize: 14,
      fontWeight: "700",
      fontFamily: fonteMono,
      color: cores.textoPrimario,
      outlineStyle: "solid",
      outlineWidth: 0,
    },
    unidadeDesconto: {
      fontSize: 13,
      fontWeight: "800",
      fontFamily: fonteMono,
      color: cores.textoTerciario,
    },
    aviso: {
      flexDirection: "row",
      alignItems: "flex-start",
      gap: 6,
      padding: 10,
      borderRadius: raios.sm,
      borderWidth: 1,
      borderColor: cores.perigoBorda,
      backgroundColor: cores.perigoFundo,
    },
    avisoTexto: {
      flex: 1,
      fontSize: 12,
      lineHeight: 17,
      fontWeight: "600",
      color: cores.perigo,
    },
    gradePagamento: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
    },
    opcaoPagamento: {
      flexGrow: 1,
      flexBasis: "45%",
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      height: ALVO_TOQUE_MINIMO + 2,
      paddingHorizontal: 12,
      borderRadius: raios.sm,
      borderWidth: 1,
      borderColor: cores.borda,
      backgroundColor: cores.superficie,
    },
    opcaoPagamentoAtiva: {
      borderColor: cores.primaria,
      backgroundColor: cores.primariaFundo,
    },
    opcaoPagamentoIcone: {
      fontSize: 15,
    },
    opcaoPagamentoTexto: {
      fontSize: 12,
      fontWeight: "600",
      color: cores.textoSecundario,
    },
    opcaoPagamentoTextoAtiva: {
      fontWeight: "800",
      color: cores.primaria,
    },
    totais: {
      gap: 6,
      paddingTop: 10,
      borderTopWidth: 1,
      borderTopColor: cores.bordaSuave,
    },
    totalLinha: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    totalRotulo: {
      fontSize: 13,
      color: cores.textoTerciario,
    },
    totalValor: {
      fontSize: 13,
      fontWeight: "600",
      fontFamily: fonteMono,
      color: cores.textoSecundario,
    },
    totalDesconto: {
      color: cores.perigo,
    },
    totalFinalLinha: {
      paddingTop: 8,
      borderTopWidth: 1,
      borderTopColor: cores.bordaSuave,
    },
    totalFinalRotulo: {
      fontSize: 14,
      fontWeight: "800",
      color: cores.textoPrimario,
    },
    totalFinalValor: {
      fontSize: 18,
      fontWeight: "800",
      fontFamily: fonteMono,
      color: cores.primaria,
    },

  });
}
