import { StyleSheet } from "react-native";

import { ALVO_TOQUE_MINIMO, fonteMono, raios, type Cores } from "@/constants/theme";

export function criarEstilos(cores: Cores) {
  return StyleSheet.create({
    container: {
      gap: 12,
    },
    flex: {
      flex: 1,
    },
    faixaEdicao: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      padding: 10,
      borderRadius: raios.sm,
      borderWidth: 1,
      borderColor: cores.primariaFundoForte,
      backgroundColor: cores.primariaFundo,
    },
    faixaEdicaoTexto: {
      flex: 1,
      fontSize: 12,
      fontWeight: "600",
      color: cores.primaria,
    },
    cabecalhoSubmodo: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    tituloSubmodo: {
      fontSize: 14,
      fontWeight: "800",
      color: cores.textoPrimario,
    },
    cartao: {
      gap: 8,
      padding: 12,
      borderRadius: raios.md,
      borderWidth: 1,
      borderColor: cores.borda,
      backgroundColor: cores.superficieAlternativa,
    },
    linhaCabecalho: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 8,
    },
    rotuloSecao: {
      fontSize: 12,
      fontWeight: "800",
      color: cores.textoSecundario,
    },
    textoSuave: {
      fontSize: 11,
      fontWeight: "400",
      color: cores.textoTerciario,
    },
    textoAjuda: {
      fontSize: 12,
      color: cores.textoTerciario,
    },
    textoPerigo: {
      color: cores.perigo,
    },
    link: {
      fontSize: 13,
      fontWeight: "700",
      color: cores.primaria,
    },
    linkPerigo: {
      marginTop: 3,
      fontSize: 11,
      fontWeight: "600",
      color: cores.perigo,
    },
    botaoSuave: {
      flexDirection: "row",
      alignItems: "center",
      gap: 3,
      height: 32,
      paddingHorizontal: 10,
      borderRadius: raios.sm,
      backgroundColor: cores.primariaFundo,
    },
    botaoSuaveTexto: {
      fontSize: 12,
      fontWeight: "700",
      color: cores.primaria,
    },
    item: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      padding: 10,
      borderRadius: raios.sm,
      borderWidth: 1,
      borderColor: cores.bordaSuave,
      backgroundColor: cores.superficie,
    },
    itemBalcao: {
      borderColor: cores.primariaFundoForte,
      backgroundColor: cores.primariaFundo,
    },
    itemIcone: {
      fontSize: 18,
    },
    itemNome: {
      fontSize: 13,
      fontWeight: "700",
      color: cores.textoPrimario,
    },
    itemDetalhe: {
      marginTop: 1,
      fontSize: 11,
      fontFamily: fonteMono,
      color: cores.textoTerciario,
    },
    itemDireita: {
      alignItems: "flex-end",
      gap: 6,
    },
    itemTotal: {
      fontSize: 13,
      fontWeight: "800",
      fontFamily: fonteMono,
      color: cores.textoPrimario,
    },
    avisoEstoque: {
      marginTop: 2,
      fontSize: 11,
      fontWeight: "700",
      color: cores.alerta,
    },
    opcoesBalcao: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 6,
    },
    opcaoBalcao: {
      minHeight: 34,
      justifyContent: "center",
      paddingHorizontal: 10,
      borderRadius: raios.sm,
      borderWidth: 1,
      borderColor: cores.primariaFundoForte,
      backgroundColor: cores.superficie,
    },
    opcaoBalcaoTexto: {
      fontSize: 11,
      fontWeight: "600",
      color: cores.primaria,
    },
    gradePagamento: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
    },
    opcaoPagamento: {
      flexGrow: 1,
      flexBasis: "45%",
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      height: ALVO_TOQUE_MINIMO,
      paddingHorizontal: 12,
      borderRadius: raios.sm,
      borderWidth: 1,
      borderColor: cores.borda,
      backgroundColor: cores.superficie,
    },
    opcaoPagamentoAtiva: {
      borderColor: cores.primaria,
      backgroundColor: cores.primariaFundo,
    },
    opcaoPagamentoTexto: {
      fontSize: 12,
      fontWeight: "600",
      color: cores.textoSecundario,
    },
    opcaoPagamentoTextoAtiva: {
      fontWeight: "800",
      color: cores.primaria,
    },
    segmentado: {
      flexDirection: "row",
      padding: 3,
      borderRadius: raios.sm - 2,
      backgroundColor: cores.neutroFundoForte,
    },
    segmento: {
      minWidth: 40,
      height: 28,
      paddingHorizontal: 8,
      borderRadius: 8,
      alignItems: "center",
      justifyContent: "center",
    },
    segmentoAtivo: {
      backgroundColor: cores.superficie,
    },
    segmentoTexto: {
      fontSize: 11,
      fontWeight: "600",
      color: cores.textoSecundario,
    },
    segmentoTextoAtivo: {
      fontWeight: "800",
      color: cores.primaria,
    },
    campoDesconto: {
      flexDirection: "row",
      alignItems: "center",
      height: ALVO_TOQUE_MINIMO,
      paddingHorizontal: 12,
      borderRadius: raios.sm,
      borderWidth: 1,
      borderColor: cores.borda,
      backgroundColor: cores.superficie,
    },
    campoDescontoErro: {
      borderColor: cores.perigo,
    },
    inputDesconto: {
      flex: 1,
      height: "100%",
      fontSize: 14,
      fontWeight: "700",
      fontFamily: fonteMono,
      color: cores.textoPrimario,
      outlineStyle: "solid",
      outlineWidth: 0,
    },
    unidade: {
      fontSize: 13,
      fontWeight: "800",
      fontFamily: fonteMono,
      color: cores.textoTerciario,
    },
    avisoPerigo: {
      fontSize: 12,
      fontWeight: "600",
      color: cores.perigo,
    },
    contador: {
      fontSize: 11,
      fontFamily: fonteMono,
      color: cores.textoTerciario,
    },
    inputObservacao: {
      minHeight: 76,
      padding: 10,
      borderRadius: raios.sm,
      borderWidth: 1,
      borderColor: cores.borda,
      backgroundColor: cores.superficie,
      fontSize: 13,
      lineHeight: 19,
      color: cores.textoPrimario,
      textAlignVertical: "top",
      outlineStyle: "solid",
      outlineWidth: 0,
    },
    campoBusca: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      height: ALVO_TOQUE_MINIMO,
      paddingHorizontal: 12,
      borderRadius: raios.md,
      borderWidth: 1,
      borderColor: cores.borda,
      backgroundColor: cores.superficie,
    },
    inputBusca: {
      flex: 1,
      height: "100%",
      fontSize: 14,
      color: cores.textoPrimario,
      outlineStyle: "solid",
      outlineWidth: 0,
    },
    resultado: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      minHeight: 54,
      paddingHorizontal: 10,
      borderRadius: raios.sm,
      borderWidth: 1,
      borderColor: cores.bordaSuave,
      backgroundColor: cores.superficie,
    },
    contadorNoPedido: {
      minWidth: 22,
      height: 22,
      paddingHorizontal: 6,
      borderRadius: raios.pill,
      backgroundColor: cores.botaoPrimario,
      alignItems: "center",
      justifyContent: "center",
    },
    contadorNoPedidoTexto: {
      fontSize: 11,
      fontWeight: "800",
      color: cores.textoSobreCor,
    },
    totais: {
      gap: 6,
      paddingTop: 4,
    },
    totalLinha: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    totalRotulo: {
      fontSize: 13,
      color: cores.textoTerciario,
    },
    totalValor: {
      fontSize: 13,
      fontFamily: fonteMono,
      color: cores.textoSecundario,
    },
    totalFinalLinha: {
      paddingTop: 8,
      borderTopWidth: 1,
      borderTopColor: cores.bordaSuave,
    },
    totalFinalRotulo: {
      fontSize: 14,
      fontWeight: "800",
      color: cores.textoPrimario,
    },
    totalFinalValor: {
      fontSize: 18,
      fontWeight: "800",
      fontFamily: fonteMono,
      color: cores.primaria,
    },
    acoes: {
      flexDirection: "row",
      gap: 10,
    },
    botaoSecundario: {
      flex: 1,
      width: undefined,
    },
    botaoPrincipal: {
      flex: 1.6,
      width: undefined,
    },
  });
}
